### PR TITLE
New End of Chapter Exercises

### PR DESCRIPTION
**Pull request by Kpatel6987**

### CODE REVIEW

**Comment by katieirenec** [comment]
Hi @Kpatel6987,

I am getting a build error when I attempt to build the ebook with your changes. I suspect that somewhere "divide" is missing an "e". Does building (runestone build) work for you? 

Exception occurred:
  File "/Users/katie/anaconda/envs/runes/lib/python2.7/site-packages/runestone/tabbedStuff/tabbedStuff.py", line 55, in visit_tab_node
    divid = node.parent.divid
AttributeError: 'list_item' object has no attribute 'divid'

Let me know what you think about the error and if building works for you.

Thanks!!

**Comment by katieirenec** [comment]
@Kpatel6987 Building your TeacherCSP with your End-of-chapter changes works for me though.

**Comment by katieirenec** [comment]
@Kpatel6987 Okay, looking at the code I think divid is div ID (nothing to do with dividing). So maybe it's a formatting issue.

Still, let me know if this builds for you. Thanks!

**Comment by Kpatel6987** [comment]
Hi,

I built the book fine, but I never touched the file where you are getting
the error.

**Comment by katieirenec** [comment]
@Kpatel6987 How weird that it would build for you but not for me! But, I think I found the problem by looking more deeply at the error and doing some diffs. There are a couple slight formatting issues in ch3_exercises.rst and ch7_exercises.rst. When I fix them, I get a successful build. I think tabbedStuff.py couldn't parse those files as it was trying to build the HTML structure.

Here are the issues:
- _sources/CSPNameNumbers/ch3_exercises.rst line 230 — discussion tab needs to be moved to the right
- _sources/CSPRepeatNumbers/ch7_exercises.rst line 445 — discussion tab needs to be moved to the right

Could you make these two formatting changes? Then I think I can merge!

Thanks!!

**Comment by Kpatel6987** [comment]
Sorry,

I thought you were talking about the TeacherCSP ebook. That is the one I
tried to build last night, not the StudentCSP. I fixed the errors in the
Student CSP, though. Thanks!

On Sat, Aug 27, 2016 at 10:59 AM, Katie Cunningham <notifications@github.com

**Comment by katieirenec** [comment]
Awesome! Builds great, thanks so much!

Merging now.

**Pull request merged**
